version: "3"

services:
  nextcloud:
    image: nextcloud:22-fpm-alpine
    environment:
      REDIS_HOST: nextcloud-redis
      REDIS_HOST_PASSWORD: ${REDIS_PW}
      POSTGRES_HOST: nextcloud-postgres
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${POSTGRES_PW}

    volumes:
      - ./data/nextcloud:/var/www/html
    depends_on:
      - nextcloud-postgres
      - nextcloud-redis
    restart: always

  nextcloud-postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${POSTGRES_PW}

    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always

  nextcloud-redis:
    image: redis:6-alpine
    command: redis-server --requirepass ${REDIS_PW}
    volumes:
      - redis_data:/data
    restart: always

  webserver:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy:/data
      - ./data/nextcloud:/var/www/html
    restart: always

volumes:
  redis_data:
    driver: local
